language: ruby
os: osx

before_install:
  - brew update

install:
  - HOMEBREW_TAP_DIR="$(brew --repo "$TRAVIS_REPO_SLUG")"
  - mkdir -p "$(dirname "$HOMEBREW_TAP_DIR")"
  - ln -s "$PWD" "$HOMEBREW_TAP_DIR"
  - brew tap --repair

env:
  - PACKAGE=dynamodb-local

script:
  - brew audit $PACKAGE
  - brew install -v $PACKAGE
  - brew test $PACKAGE
